using Blazor.Markdown.Core.DAL.Entity;
using MongoDB.Bson.Serialization;
using MongoDB.Bson.Serialization.IdGenerators;

namespace Blazor.Markdown.Core.DAL.Mongo.Map
{
    public class SettingsMap : BsonClassMap<Settings>
    {
        public SettingsMap()
        {
            this.MapIdMember(x => x.Id).SetOrder(1).SetIdGenerator(CombGuidGenerator.Instance);

            this.MapMember(x => x.ConnectionString).SetOrder(2).SetDefaultValue("mongodb://localhost:27017").SetIsRequired(true);
            this.MapMember(x => x.DateAdded).SetOrder(3).SetIsRequired(true);
            this.MapMember(x => x.DateLastUpdated).SetOrder(4).SetIsRequired(true);

            // This is to ignore the ObjectId generated by MongoDB.
            this.SetIgnoreExtraElements(true);

            RegisterClassMap(this);
        }
    }
}
