using Blazor.Markdown.Core.DAL.Entity;
using Blazor.Markdown.Core.DAL.Providers.Mongo;
using MongoDB.Bson.Serialization;
using MongoDB.Bson.Serialization.IdGenerators;

namespace Blazor.Markdown.Core.DAL.Mongo.Map
{
    public class SettingsMap : RegisterMap<Settings>
    {
        public SettingsMap()
        {

        }

        public override void Configure(BsonClassMap<Settings> builder)
        {
            builder.MapIdMember(x => x.Id).SetOrder(1).SetIdGenerator(CombGuidGenerator.Instance);

            builder.MapMember(x => x.ConnectionString).SetOrder(2).SetDefaultValue("mongodb://localhost:27017").SetIsRequired(true);
            builder.MapMember(x => x.DateAdded).SetOrder(3).SetIsRequired(true);
            builder.MapMember(x => x.DateLastUpdated).SetOrder(4).SetIsRequired(true);

            // This is to ignore the ObjectId generated by MongoDB.
            builder.SetIgnoreExtraElements(true);
        }
    }
}
